#!/usr/bin/env python3.6

import subprocess 

def find_network_ip():
    network_ip = subprocess.run(["ifconfig","-a"], stdout=subprocess.PIPE)

    network_ip_output = str(network_ip.stdout).split()

    for y in range(len(network_ip_output)):
        network_ip_output[y].strip("\n")
        #if network_ip_output[y] == "ens3:":
        print(network_ip_output[y])

    #return network_ip_output


def return_win_ip():
    proc = subprocess.run(["arp","-a"], stdout=subprocess.PIPE)

    output = str(proc.stdout).split()

    for x in range(len(output)):
        if output[x] == "70:85:c2:8c:37:8c":
            return output[x-2]


#print(return_win_ip())
print(find_network_ip())

