#!/usr/bin/env python3.6

import subprocess 

def return_win_ip():
    proc = subprocess.run(["arp","-a"], stdout=subprocess.PIPE)

    output = str(proc.stdout).split()

    for x in range(len(output)):
        if output[x] == "70:85:c2:8c:37:8c":
            return output[x-2]


print(return_win_ip())
