#!/usr/bin/env python3.6

import subprocess 

def find_network_ip():
    network_ip = subprocess.run(["ifconfig","-a"], stdout=subprocess.PIPE)

    network_ip_output = str(network_ip.stdout).split()

    for y in range(len(network_ip_output)):
        if network_ip_output[y][5::] == "ens3:" or network_ip_output[y][5::] == "eth0:":
            return network_ip_output[y + 5]

# fun to set the address of the ip to be broadcasted to based on the local nic address
def set_broadcast_address(ip):
    print(ip)

# fun that will broadcast to the local network to find all the ips
def broadcast():
    pass

def return_win_ip():
    proc = subprocess.run(["arp","-a"], stdout=subprocess.PIPE)

    output = str(proc.stdout).split()

    for x in range(len(output)):
        if output[x] == "70:85:c2:8c:37:8c":
            return output[x-2][1:-1]


#print(return_win_ip())
#print(find_network_ip())
print(set_broadcast_address(find_network_ip()))
